Bugfix: Updates were not applied correctly.
Branches were synced with remote ones but not the working directory;
that is fixed now.
Improved handling of unpushed changes (for example when no network
connection was available when updating files): Branches are merged and
not reset any more.
Uncomitted changes are stashed before applying any other changes and
restored afterwards.

diff --git a/config-update b/config-update
--- a/config-update
+++ b/config-update
@@ -86,8 +86,7 @@ config-update () {
             esac
             shift
         done
-        if [[ "$1" = "" && (! -d "${CONFIGS_DIR}" || \
-              "$(cd "${CONFIGS_DIR}" && git ls-files --modified)" = "") ]]; then
+        if [[ "$1" = "" ]]; then
             FETCH_REMOTE_ONLY=1
         else
             FETCH_REMOTE_ONLY=0
@@ -122,8 +121,10 @@ config-update () {
     }
 
     create_working_copy_and_fetch_remote_configs () {
-        local return_code fetched_only ref local_branch local_branches remote_branch branches_to_verify
+        local return_code fetched_only stashed_changes ref local_branch local_branches remote_branch branches_to_verify
         local prompt_script_path base_branch
+
+        return_code=0
 
         [[ "${CONFIG_UPDATE_CONFIGS_REPO_URL}" != "" ]] || \
             { ERROR_OUTPUT="The variable ${BOLD_LIGHT_MAGENTA}CONFIG_UPDATE_CONFIGS_REPO_URL${NC} is not set."; \
@@ -139,13 +140,19 @@ config-update () {
         fi
 
         # Fetch remote changes
-        if [[ "$(cd "${CONFIGS_WORKING_DIR}" 2>/dev/null && \
-          git remote -v | awk '$1 == "origin" && $3 == "(fetch)" { print $2 }')" == \
-          "${CONFIG_UPDATE_CONFIGS_REPO_URL}" ]]; then
+        if [[ -d "${CONFIGS_WORKING_DIR}" ]]; then
             pushd "${CONFIGS_WORKING_DIR}" >/dev/null 2>&1 && \
-            git fetch origin >/dev/null 2>&1 && \
-            git remote prune origin
-            return_code="$?"
+            # Check if the user has configured a new fetch URL
+            if [[ "$(git remote -v | awk '$1 == "origin" && $3 == "(fetch)" { print $2 }')" != \
+              "${CONFIG_UPDATE_CONFIGS_REPO_URL}" ]]; then
+                git remote set-url origin "${CONFIG_UPDATE_CONFIGS_REPO_URL}"
+                return_code="$?"
+            fi
+            if [[ "${return_code}" -eq 0 ]]; then
+                git fetch origin >/dev/null 2>&1 && \
+                git remote prune origin
+                return_code="$?"
+            fi
             fetched_only=1
         else
             rm -rf "${CONFIGS_WORKING_DIR}" && \
@@ -157,64 +164,102 @@ config-update () {
         fi
         [[ "${return_code}" -eq 0 ]] || { ERROR_OUTPUT="Could not fetch remote changes."; return 5; }
 
-        # Guarantee that all remote branches are checked out as local tracking branches
-        if [[ "${return_code}" -eq 0 ]]; then
-            for ref in $(git for-each-ref --format='%(refname)' refs/remotes/origin/); do
-                [[ "${ref}" != "refs/remotes/origin/HEAD" ]] || continue
-                local_branch="$(echo "${ref}" | awk -F'/' '{ print $NF }')" && \
-                remote_branch="origin/${local_branch}" && \
-                git update-ref "refs/heads/${local_branch}" "${ref}" && \
-                git branch --set-upstream-to "${remote_branch}" "${local_branch}" >/dev/null 2>&1
+        # Check for local changes that have not been committed yet
+        if [[ "$(git status --porcelain | awk '$1 != "??" { print $0 }')" != "" ]]; then
+            git stash >/dev/null 2>&1 || \
+                { ERROR_OUTPUT="Could not stash local changes in the config repository."; return 6; }
+            stashed_changes=1
+        else
+            stashed_changes=0
+        fi
+
+        # Update local branches and guarantee that all remote branches are checked out as local tracking branches
+        for ref in $(git for-each-ref --format='%(refname)' refs/remotes/origin/); do
+            [[ "${ref}" != "refs/remotes/origin/HEAD" ]] || continue
+            local_branch="$(echo "${ref}" | awk -F'/' '{ print $NF }')" && \
+            remote_branch="origin/${local_branch}" && \
+            if ! git show-ref --quiet --verify "refs/heads/${local_branch}"; then
+                git update-ref "refs/heads/${local_branch}" "${ref}"
                 return_code="$?"
                 [[ "${return_code}" -eq 0 ]] || break
-            done
+            fi
+            git branch --set-upstream-to "${remote_branch}" "${local_branch}" >/dev/null 2>&1 && \
+            git checkout "${local_branch}" >/dev/null 2>&1
+            return_code="$?"
+            [[ "${return_code}" -eq 0 ]] || break
+            if ! git merge --no-edit "${remote_branch}" >/dev/null 2>&1; then
+                echo -e "Automerging failed. Please resolve conflicts for the branch" \
+                    "${BOLD_LIGHT_CYAN}${local_branch}${NC}."
+                read -n 1 -p "Continue?" && \
+                git mergetool && \
+                git commit -a
+                return_code="$?"
+                [[ "${return_code}" -eq 0 ]] || break
+            fi
+        done
+        [[ "${return_code}" -eq 0 ]] || \
+            { ERROR_OUTPUT="Could not update local branches with remote changes."; return 7; }
+
+        # Sync the working tree with fetched changes
+        git checkout "${CONFIG_UPDATE_BRANCH}" >/dev/null 2>&1 && \
+        git reset --hard HEAD >/dev/null 2>&1 || \
+            { ERROR_OUTPUT="Could not sync the local working tree with fetched changes"; return 8; }
+
+        # Apply stashed changes if any
+        if (( stashed_changes )); then
+            if ! git stash pop >/dev/null 2>&1; then
+                echo -e "Applying stashed changes failed. Please resolve conflicts."
+                read -n 1 -p "Continue?" && \
+                git mergetool && \
+                git reset && \
+                git stash drop
+                return_code="$?"
+            fi
         fi
         [[ "${return_code}" -eq 0 ]] || \
-            { ERROR_OUTPUT="Could not setup config branches as local tracking branches."; return 6; }
+            { ERROR_OUTPUT="Could not apply stashed changes."; return 9; }
 
         # Verify that required refs (`master`, `${CONFIG_UPDATE_BRANCH}` and `${EDIT_BRANCH}`) exist
-        if [[ "${return_code}" -eq 0 ]]; then
-            local_branches=()
-            for ref in $(git for-each-ref --format='%(refname)' refs/heads/); do
-                [[ "${ref}" != "refs/heads/HEAD" ]] || continue
-                local_branch="$(echo "${ref}" | awk -F'/' '{ print $NF }')" && \
-                local_branches+=( "${local_branch}" )
-            done
-            branches_to_verify=( "master" "${CONFIG_UPDATE_BRANCH}" )
-            if [[ -n "${EDIT_BRANCH}" ]]; then
-                branches_to_verify+=( "${EDIT_BRANCH}" )
-            fi
-            for local_branch in "${branches_to_verify[@]}"; do
-                git show-ref --quiet --verify "refs/heads/${local_branch}"
-                return_code="$?"
-                if [[ "${return_code}" -ne 0 ]]; then
-                    [[ "${local_branch}" != "master" ]] || \
-                        { ERROR_OUTPUT="Local branch ${BOLD_LIGHT_CYAN}${local_branch}${NC} is missing."; break; }
-                    echo -e "The required branch ${BOLD_LIGHT_CYAN}${local_branch}${NC} does not exist." \
-                        "On which ${BOLD_LIGHT_GREEN}branch${NC} should it be based on?\n (tab completion is enabled)"
-                    prompt_script_path="$(write_prompt_script)"
-                    return_code="$?"
-                    [[ "${return_code}" -eq 0 ]] || \
-                        { ERROR_OUTPUT="Internal error, could not create temporary script file."; break; }
-                    while true; do
-                        base_branch="$("${prompt_script_path}" "${local_branches[@]}")" || return 7
-                        git show-ref --quiet --verify "refs/heads/${base_branch}" && break
-                        echo -e "The branch ${BOLD_LIGHT_CYAN}${base_branch}${NC} does not exist." \
-                            "Please correct your input:"
-                    done
-                    rm -rf "$(dirname "${prompt_script_path}")"
-                    git update-ref "refs/heads/${local_branch}" "refs/heads/${base_branch}" && \
-                    git push -u origin "${local_branch}"
-                    return_code="$?"
-                    [[ "${return_code}" -eq 0 ]] || \
-                        { ERROR_OUTPUT="Could not create a new branch ${BOLD_LIGHT_CYAN}${local_branch}${NC}"; break; }
-                    if [[ "${local_branch}" = "${EDIT_BRANCH}" ]]; then
-                        CREATED_EDIT_BRANCH=1
-                    fi
-                fi
-            done
+        local_branches=()
+        for ref in $(git for-each-ref --format='%(refname)' refs/heads/); do
+            [[ "${ref}" != "refs/heads/HEAD" ]] || continue
+            local_branch="$(echo "${ref}" | awk -F'/' '{ print $NF }')" && \
+            local_branches+=( "${local_branch}" )
+        done
+        branches_to_verify=( "master" "${CONFIG_UPDATE_BRANCH}" )
+        if [[ -n "${EDIT_BRANCH}" ]]; then
+            branches_to_verify+=( "${EDIT_BRANCH}" )
         fi
-        [[ "${return_code}" -eq 0 ]] || return 7
+        for local_branch in "${branches_to_verify[@]}"; do
+            git show-ref --quiet --verify "refs/heads/${local_branch}"
+            return_code="$?"
+            if [[ "${return_code}" -ne 0 ]]; then
+                [[ "${local_branch}" != "master" ]] || \
+                    { ERROR_OUTPUT="Local branch ${BOLD_LIGHT_CYAN}${local_branch}${NC} is missing."; break; }
+                echo -e "The required branch ${BOLD_LIGHT_CYAN}${local_branch}${NC} does not exist." \
+                    "On which ${BOLD_LIGHT_GREEN}branch${NC} should it be based on?\n (tab completion is enabled)"
+                prompt_script_path="$(write_prompt_script)"
+                return_code="$?"
+                [[ "${return_code}" -eq 0 ]] || \
+                    { ERROR_OUTPUT="Internal error, could not create temporary script file."; break; }
+                while true; do
+                    base_branch="$("${prompt_script_path}" "${local_branches[@]}")" || return 10
+                    git show-ref --quiet --verify "refs/heads/${base_branch}" && break
+                    echo -e "The branch ${BOLD_LIGHT_CYAN}${base_branch}${NC} does not exist." \
+                        "Please correct your input:"
+                done
+                rm -rf "$(dirname "${prompt_script_path}")"
+                git update-ref "refs/heads/${local_branch}" "refs/heads/${base_branch}" && \
+                git push -u origin "${local_branch}"
+                return_code="$?"
+                [[ "${return_code}" -eq 0 ]] || \
+                    { ERROR_OUTPUT="Could not create a new branch ${BOLD_LIGHT_CYAN}${local_branch}${NC}"; break; }
+                if [[ "${local_branch}" = "${EDIT_BRANCH}" ]]; then
+                    CREATED_EDIT_BRANCH=1
+                fi
+            fi
+        done
+        [[ "${return_code}" -eq 0 ]] || return 10
 
         # Show diff stats if the local repository existed before
         if (( fetched_only )); then
@@ -222,6 +267,9 @@ config-update () {
         fi
 
         echo "Set up a working copy of the config directory and fetched remote changes."
+        if (( stashed_changes )); then
+            echo "Restored uncommitted changes."
+        fi
         return 0
     }
 
@@ -250,7 +298,7 @@ config-update () {
             else
                 read -e -p '> ' -i "${config_filepath}" config_filepath
             fi
-            [[ "$?" -eq 0 ]] || { popd >/dev/null 2>&1; return 8; }
+            [[ "$?" -eq 0 ]] || { popd >/dev/null 2>&1; return 11; }
             [[ -f "${config_filepath}" ]] && break
             echo -e "The file ${BOLD_LIGHT_BLUE}${config_filepath}${NC} does not exist. Please correct your input:"
         done
@@ -258,15 +306,15 @@ config-update () {
         popd >/dev/null 2>&1
         mkdir -p "$(dirname "${CONFIG_FILENAME}")" || \
             { ERROR_OUTPUT="The directory ${BOLD_LIGHT_BLUE}$(dirname "${CONFIG_FILENAME}")${NC} could not be created."; \
-              return 9; }
+              return 12; }
         cp "${config_absolute_filepath}" "${CONFIG_FILENAME}" || \
             { ERROR_OUTPUT="The config file ${BOLD_LIGHT_BLUE}${config_filepath}${NC} could not be copied into the repository."; \
-              return 10; }
+              return 13; }
         echo "${CONFIG_FILENAME}:${config_filepath}" >> "${CONFIGS_LOCATION_FILE}" && \
         git add -f "${CONFIGS_LOCATION_FILE}"
         [[ "$?" -eq 0 ]] || \
             { ERROR_OUTPUT="${BOLD_LIGHT_BLUE}${CONFIG_FILENAME}${NC} could not be added to the locations file."; \
-              return 11; }
+              return 14; }
 
         echo -e "Added the config file ${BOLD_LIGHT_BLUE}${config_filepath}${NC} to the repository."
         return 0
@@ -276,13 +324,13 @@ config-update () {
         [[ -z "${CONFIG_FILENAME}" ]] && return 0
         git checkout "${EDIT_BRANCH}" >/dev/null 2>&1 || \
             { ERROR_OUTPUT="The branch ${BOLD_LIGHT_CYAN}${EDIT_BRANCH}${NC} that should be updated cannot be checked out."; \
-              return 12; }
+              return 15; }
         [[ -d "$(dirname "${CONFIG_FILENAME}")" ]] || mkdir -p "$(dirname "${CONFIG_FILENAME}")" || \
             { ERROR_OUTPUT="The directory ${BOLD_LIGHT_BLUE}$(dirname "${CONFIG_FILENAME}")${NC} cannot be created."; \
-              return 13; }
-        ${VISUAL} "${CONFIG_FILENAME}" || { ERROR_OUTPUT="Your editor exited with a non-zero exit code."; return 14; }
+              return 16; }
+        ${VISUAL} "${CONFIG_FILENAME}" || { ERROR_OUTPUT="Your editor exited with a non-zero exit code."; return 17; }
         git add -f "${CONFIG_FILENAME}" && \
-        git commit || { ERROR_OUTPUT="Could not commit changes."; return 15; }
+        git commit || { ERROR_OUTPUT="Could not commit changes."; return 18; }
 
         echo -e "Committed changes to ${BOLD_LIGHT_BLUE}${CONFIG_FILENAME}${NC}."
         return 0
@@ -323,11 +371,14 @@ config-update () {
             # -> The change (commit) is propagated step by step
             for descendant in "${closest_descendants[@]}"; do
                 git checkout "${descendant}" >/dev/null 2>&1 || \
-                    { ERROR_OUTPUT="Could not check out ${BOLD_LIGHT_CYAN}${descendant}${NC} for merging."; return 16; }
-                if ! git merge --no-edit "${base_branch}"; then
+                    { ERROR_OUTPUT="Could not check out ${BOLD_LIGHT_CYAN}${descendant}${NC} for merging."; return 19; }
+                if ! git merge --no-edit "${base_branch}" >/dev/null 2>&1; then
+                    echo -e "Automerging failed. Please resolve conflicts for the branch" \
+                        "${BOLD_LIGHT_CYAN}${descendant}${NC}."
+                    read -n 1 -p "Continue?" && \
                     git mergetool && \
                     git commit -a
-                    [[ "$?" -eq 0 ]] || { ERROR_OUTPUT="Merge is not completed"; return 17; }
+                    [[ "$?" -eq 0 ]] || { ERROR_OUTPUT="Merge is not completed"; return 20; }
                 fi
                 echo -e "Merged ${BOLD_LIGHT_CYAN}${base_branch}${NC} into ${BOLD_LIGHT_CYAN}${descendant}${NC}."
                 merge_config_recursive "${descendant}"
@@ -341,19 +392,17 @@ config-update () {
     }
 
     push_config () {
-        git push || { ERROR_OUTPUT="Pushing new commits failed"; return 18; }
+        git push || { ERROR_OUTPUT="Pushing new commits failed"; return 21; }
     }
 
     apply_working_copy_changes () {
-        local return_code
-
         git checkout "${CONFIG_UPDATE_BRANCH}" >/dev/null 2>&1 || \
-            { ERROR_OUTPUT="Could not checkout ${BOLD_LIGHT_CYAN}${CONFIG_UPDATE_BRANCH}${NC}."; return 19; }
+            { ERROR_OUTPUT="Could not checkout ${BOLD_LIGHT_CYAN}${CONFIG_UPDATE_BRANCH}${NC}."; return 22; }
         pushd .. >/dev/null 2>&1 && \
         rm -rf "${CONFIGS_DIR}" && \
         cp -r "${CONFIGS_WORKING_DIR}" "${CONFIGS_DIR}" && \
         popd >/dev/null 2>&1
-        [[ "$?" -eq 0 ]] || { ERROR_OUTPUT="Could not apply working copy changes (copy failed)."; return 20; }
+        [[ "$?" -eq 0 ]] || { ERROR_OUTPUT="Could not apply working copy changes (copy failed)."; return 23; }
 
         echo "Applied the working copy changes to the real config files."
         return 0
@@ -376,17 +425,17 @@ config-update () {
                     ln -s "${CONFIGS_DIR}/${config_name}" "${config_filepath}"
                     [[ "$?" -eq 0 ]] || \
                         { ERROR_OUTPUT="Could not modify the existing symbolic link ${BOLD_LIGHT_BLUE}${config_filepath}${NC}."; \
-                          return 21; }
+                          return 24; }
                 fi
             else
                 if [[ -f "${config_filepath}" ]]; then
                     mv "${config_filepath}" "${config_filepath}.bak" || \
                         { ERROR_OUTPUT="Could not create a backup of the old config file ${BOLD_LIGHT_BLUE}${config_filepath}${NC}."; \
-                          return 22; }
+                          return 25; }
                 fi
                 ln -s "${CONFIGS_DIR}/${config_name}" "${config_filepath}" || \
                     { ERROR_OUTPUT="Could not create a symbolic link for the config file ${BOLD_LIGHT_BLUE}${config_filepath}${NC}."; \
-                      return 23; }
+                      return 26; }
             fi
         done
 
@@ -396,7 +445,7 @@ config-update () {
 
     cleanup () {
         popd >/dev/null 2>&1
-        rm -rf "${CONFIGS_WORKING_DIR}" || { ERROR_OUTPUT="Could not cleanup the working directory"; return 24; }
+        rm -rf "${CONFIGS_WORKING_DIR}" || { ERROR_OUTPUT="Could not cleanup the working directory"; return 27; }
 
         echo "Cleaned the working directory."
         return 0
